### PR TITLE
Remove the sleeps now that rate limiting is gone

### PR DESCRIPTION
**Pull request by matthewcummings**

### CODE REVIEW

**Comment by andreylarionov** [comment]
I guess it's better to leave as it is.

**Comment by matthewcummings** [comment]
Really?  That seems confusing to me now that you're moving from a model with rate limiting to one without it.

**Comment by matthewcummings** [comment]
If we leave the sleeps in the example scripts, what do say about them?  That they're there to prevent the user from overloading the server?  That doesn't sound good, it sounds like TextMagic won't scale well.

**Comment by andreylarionov** [comment]
We have reduced the rate limit value but we did not cancel it completely. It will be documented soon.

**Comment by matthewcummings** [comment]
OK, thanks.

**Pull request closed without merging**
